import type { DmeRmsConfigStation } from "../dme-types";

export type DmeChannelType = DmeRmsConfigStation["channelType"];

export interface DmeChannelAllocation {
  channelNumber: number;
  channelType: DmeChannelType;
  channelLabel: string;
  monitorInterrogatorFrequencyMHz: number;
  receiverFrequencyMHz: number;
  receiverLoFrequencyMHz: number;
  transmitterReplyFrequencyMHz: number;
  interrogatorPulseSpacingUs: 12 | 36;
  transmitterReplyPulseSpacingUs: 12 | 30;
  nominalReplyDelayUs: 50 | 56;
}

/**
 * Resolves the 1118A/1119A channel plan from O&M Manual table 9-5.
 *
 * The station receives the aircraft interrogation at the same assigned
 * frequency generated by the monitor interrogator. The RTC receiver LO is
 * 125 MHz below that assigned receive frequency (manual section 6.2.1).
 */
export function getDmeChannelAllocation(
  channelNumber: number,
  channelType: DmeChannelType,
): DmeChannelAllocation | null {
  if (!Number.isInteger(channelNumber) || channelNumber < 1 || channelNumber > 126) {
    return null;
  }

  const upperReplyBand = channelType === "X" ? channelNumber >= 64 : channelNumber <= 63;
  const monitorInterrogatorFrequencyMHz = 1024 + channelNumber;

  return {
    channelNumber,
    channelType,
    channelLabel: `${channelNumber}${channelType}`,
    monitorInterrogatorFrequencyMHz,
    receiverFrequencyMHz: monitorInterrogatorFrequencyMHz,
    receiverLoFrequencyMHz: 899 + channelNumber,
    transmitterReplyFrequencyMHz: channelNumber + (upperReplyBand ? 1087 : 961),
    interrogatorPulseSpacingUs: channelType === "X" ? 12 : 36,
    transmitterReplyPulseSpacingUs: channelType === "X" ? 12 : 30,
    nominalReplyDelayUs: channelType === "X" ? 50 : 56,
  };
}

export function getDmeStationChannelAllocation(
  station: Pick<DmeRmsConfigStation, "channelNumber" | "channelType">,
): DmeChannelAllocation | null {
  return getDmeChannelAllocation(station.channelNumber, station.channelType);
}

export function formatDmeFrequency(frequencyMHz: number): string {
  return frequencyMHz.toFixed(3);
}
